server:
  port: 7054
  servlet:
    context-path: /
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          temp:
            use_jdbc_metadata_defaults: true
        hbm2ddl:
          auto: update
  datasource:
    username: ${MSQLLOGIN:root}
    password: ${MSQLPASS:4bbak$~X=mcr}
    url: jdbc:mysql://${MSQLSERVER:34.133.197.241}:${MSQLPORT:3306}/products
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1900000

