server:
  port: 7054
  servlet:
    context-path: /
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          temp:
            use_jdbc_metadata_defaults: true
        hbm2ddl:
          auto: update
  datasource:
    username: ${PSQLLOGIN:root}
    password: ${PSQLPASS:root}
    url: jdbc:mysql://${PSQLSERVER:localhost}:${PSQLPORT:3306}/products
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1000000

