server:
  port: 7054
  servlet:
    context-path: /
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          temp:
            use_jdbc_metadata_defaults: true
        hbm2ddl:
          auto: update
  datasource:
    username: root
    password: zalupakonskaya6869
    url: jdbc:mysql://194.58.120.217:5555/products
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
