server:
  port: 7054
  servlet:
    context-path: /
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          temp:
            use_jdbc_metadata_defaults: true
        hbm2ddl:
          auto: create
    show-sql: false
  datasource:
    username: ${MSQL_LOGIN:root}
    password: ${MSQL_PASS:root}
    url: jdbc:mysql://${MSQL_SERVER:localhost}:${MSQL_PORT:3306}/products
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1900000

